/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    BasicConfig: typeof import('./src/components/BasicConfig.vue')['default']
    CodeExplorer: typeof import('./src/components/CodeExplorer.vue')['default']
    CodePreviewModal: typeof import('./src/components/CodePreviewModal.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTree: typeof import('element-plus/es')['ElTree']
    FileTreePreview: typeof import('./src/components/FileTreePreview.vue')['default']
    GenerateButton: typeof import('./src/components/GenerateButton.vue')['default']
    ModuleSelector: typeof import('./src/components/ModuleSelector.vue')['default']
    QualityConfig: typeof import('./src/components/QualityConfig.vue')['default']
    SelectCardGroup: typeof import('./src/components/SelectCardGroup.vue')['default']
    SummaryCard: typeof import('./src/components/SummaryCard.vue')['default']
    ToastView: typeof import('./src/components/ToastView.vue')['default']
  }
}
